import React from 'react'

function Faq() {
    return (
        <div id="faq">
            <h1 className="animated fadeInLeftBig">Frequently Asked Questions</h1>
            <div className="container">
                <p><strong>What is a batch freezer?</strong> A batch freezer is a large freezing chamber that mixes, agitates and freezes whatever is put into it. The modern day batch freezer was first invented and patented by my Grandfather, Emery Thompson, over one hundred years ago – long before the first Italian Gelato ice cream machine was ever built.</p>
                <p><strong>What size batch freezers does Emery Thompson manufacture?</strong> We build our machines in finished capacities of 2 quart, 3 quart, 6 quart, 12 quart, 24 quart and the world’s largest batch freezer – 44 quart. We are the only company that builds their machines from the ground up to match your electrical requirements. That means Emery Thompson batch freezers are available in single phase or three phase; water or air cooled; 60 or 50 cycle and 220 or 380 volt. Our 2 quart and 3 quart batch freezers are even available in 115V "Plug In" Power!</p>
                <p><strong>Where are Emery Thompson Batch Freezers manufactured?</strong> We are proud to be 100% Made In The U.S.A. using American Labor, American manufactured components and wholly owned by my family! No other company can make this claim: not Electro-Freeze, not Carpigiani, not Stoelting, not Technogel, not even Taylor!</p>
                <p><strong>How durable are your machines?</strong> The average lifespan of an Emery Thompson is 40 years or more. All the other machines on the market are happy if they last 11 years. Our machines are hand made to your order from cast stainless steel components. Others fabricate their parts and they just don’t hold up. Our condensing units are the world’s best American made Copeland units and our transmissions and drive motors are also Made In The USA</p>
                <p><strong>Why do Emery Thompson’s cost less than other batch freezers!</strong> We are a family business and thus not top heavy with technocrats. You buy direct from us! All the other manufacturers are European and thus subject to a 40% higher Euro vs. the Dollar. You will also pay import duties and costly shipping charges. We have listed our “Direct To The Customer” price list here on our web site. This also helps to keep our spare parts a whole lot less expensive than anyone else.</p>
                <p><strong>What about used?</strong> We never see used equipment available. Our customers do not go out of business. For every 20 "other" batch freezers that show up on eBay, there is only one Emery Thompson offered for sale. Please take the time to read our article called “ET on E Bay.” The batch freezer is the life blood of your business…your key to success…an investment in your business. A recent survey of ice cream owners who were asked what their major mistake in business was said, “ buying a used batch freezer.”</p>
                <p><strong>What if I need service?</strong> Unlike any other piece of equipment you have owned, the Emery Thompson Batch Freezer should not require any service for its first ten years of life. A bold statement, but true! If something isn’t going right, first call our factory and we’ll solve your problem for you. Since we only make changes in our machines to improve on their quality, our machines are not subject to constant problem-creating style changes. We also keep our electronics as simple and thus as trouble free as humanly possible. No gadgets on an Emery Thompson! If the factory is closed for the day or on a weekend, I give my home telephone number to every one of our customers. When you call our factory 718-588-7300 a live person will answer! If you call after business hours or if it's the weekend, you will be directed to call my home telephone number! We are serious about giving you the best service, the best advice, the lowest prices and the fastest response of any company in the dairy industry!</p>
                <p><strong>Where can I learn how to make ice cream and other frozen desserts?</strong> Personally, I think this is the easiest part of opening your new business. I will gladly instruct you on how to run your new machine and supply you with all the necessary formulations. We are also associated with the world’s most renowned teaching school – Ice Cream University which has courses at convenient locations throughout the United States. In addition to Ice Cream University, we have machinery at Penn State University, University of Florida, University of Wisconsin, University of Missouri, Clemson University, Rutgers University, University of Nebraska and The University of Maryland</p>
                <p><strong>Why not sell soft-serve?</strong> People who love ice cream want ice cream, not soft-serve. But here's a cautionary tale from one store owner that's representative of why Emery Thompson doesn't build soft serve machines!:</p>
                <p style={{ fontStyle: 'italic' }}>"I have two stores, one is 75% soft serve and the other is all homemade ice cream. If anyone would like to buy a soft serve store, please let me know. They’re a lot of work! Not that any food business isn’t. The maintenance and cleaning of the machines alone is enough to keep me from ever buying another soft serve machine. It’s an hour or more each week per machine. Then seals break, blades have to be replaced, belts go out, in the middle of a busy rush the machine may not be able to freeze product as fast as you're pulling it.  And then there is training the staff… You would think twirling a cone is pretty simple, but not everyone gets it.  The profit margins may be higher, but by the time you figure in waste, time cleaning, and all the other issues I’m not sure it’s enough to be worth it. <br />
                My advice, for what it’s worth, if you don’t have to get into soft serve don’t. You don’t want the headache. " <br />
                Paul - browndogcreamery.com
                </p>
                <h4>I’m certain there must be more questions that I can answer for you. Please don’t hesitate to call me at 718-588-7300 or eMail me at steve@emerythompson.com <br/> <br/> Steve Thompson <br/> President / CEO
                </h4>
            </div>
        </div>
    )
}

export default Faq
